/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;

import java.util.LinkedList;
import java.util.Random;
import java.util.Scanner; // 1. Scannerをインポート

public class App {
  final static Random random = new Random();
  final static int maxRandomNumber = 4;// ランダムな数値の最大値(0～4)

  public String getGreeting() {
    return "Hello SEMonster";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());

    // 1. プレイヤー名の入力機能を追加
    Scanner scanner = new Scanner(System.in);
    System.out.print("プレイヤー名を入力してください > ");
    String playerName = scanner.next();

    // ゲームの準備 (モンスターを引くために必要な乱数を多めに生成)
    SeMonsterGame mf = new SeMonsterGame(createRandomList(20));

    // プレイヤーとCPUを追加
    mf.addPlayer(playerName);
    mf.addPlayer("CPU");

    // それぞれがモンスターを引く
    mf.draw(playerName);
    mf.draw("CPU");

    // 3. バトルを開始
    mf.battle(playerName, "CPU");

    scanner.close();
  }

  /**
   * 指定した数の0~4(maxRandomNumber)のランダムな数値を作成し，LinkedListに格納して返却する
   *
   * @param count
   * @return
   */
  public static LinkedList<Integer> createRandomList(int count) {
    LinkedList<Integer> randNumList = new LinkedList<>();
    for (int i = 0; i < count; i++) {
      randNumList.add(random.nextInt(maxRandomNumber + 1));
    }

    return randNumList;
  }
}